
#python run_benchmark_tests.py --strategy ilp --sub-strategy ngram --model /data/model/deepseek-aiDeepSeek-R1-Distill-Qwen-7B         --dataset-name sharegpt         --dataset-path /data/sharegpt.json   --num-prompts 442 --request-rate 10 1>> a120new.log 2>> a120new_error.log 
python run_benchmark_tests.py --strategy ilp --sub-strategy deep --model /data/model/deepseek-aiDeepSeek-R1-Distill-Qwen-7B --draft-model /data/model/DeepSeek-R1-DRAFT-Qwen2.5-0.5B       --dataset-name sharegpt         --dataset-path /data/sharegpt.json   --speculative-len 4 --num-prompts 440 --request-rate 10 &>> a131new.log
python run_benchmark_tests.py --strategy ilp --sub-strategy nospec --model /data/model/deepseek-aiDeepSeek-R1-Distill-Qwen-7B --draft-model /data/model/DeepSeek-R1-DRAFT-Qwen2.5-0.5B       --dataset-name sharegpt         --dataset-path /data/sharegpt.json   --speculative-len 4 --num-prompts 440 --request-rate 10 &>> a131new.log
# python run_benchmark_tests.py --strategy ilp --sub-strategy daspec --model /data/model/deepseek-aiDeepSeek-R1-Distill-Qwen-7B --draft-model /data/model/DeepSeek-R1-DRAFT-Qwen2.5-0.5B       --dataset-name sharegpt         --dataset-path /data/sharegpt.json   --speculative-len 4 --num-prompts 640 --request-rate 10 &>> a131new.log

# python run_benchmark_tests.py --strategy ilp --sub-strategy deep --model /hy-tmp/ --draft-model /hy-tmp/DeepSeek-R1-DRAFT-Qwen2.5-0.5B       --dataset-name sharegpt         --dataset-path /hy-tmp/sharegpt.json   --profile --speculative-len 1 --num-prompts 300 --request-rate 10 1>> a122new.log 2>> a122new_error.log 
# python run_benchmark_tests.py --strategy ilp --sub-strategy deep --model /hy-tmp/ --draft-model /hy-tmp/DeepSeek-R1-DRAFT-Qwen2.5-0.5B       --dataset-name sharegpt         --dataset-path /hy-tmp/sharegpt.json   --profile --speculative-len 2 --num-prompts 300 --request-rate 10 1>> a122new.log 2>> a122new_error.log 
# python run_benchmark_tests.py --strategy ilp --sub-strategy deep --model /hy-tmp/ --draft-model /hy-tmp/DeepSeek-R1-DRAFT-Qwen2.5-0.5B       --dataset-name sharegpt         --dataset-path /hy-tmp/sharegpt.json   --profile --speculative-len 3 --num-prompts 300 --request-rate 10 1>> a122new.log 2>> a122new_error.log 
# python run_benchmark_tests.py --strategy ilp --sub-strategy deep --model /hy-tmp/ --draft-model /hy-tmp/DeepSeek-R1-DRAFT-Qwen2.5-0.5B       --dataset-name sharegpt         --dataset-path /hy-tmp/sharegpt.json   --profile --speculative-len 4 --num-prompts 300 --request-rate 10 1>> a122new.log 2>> a122new_error.log 

# python run_benchmark_tests.py --strategy ilp --sub-strategy  nospec --model /hy-tmp/ --draft-model /hy-tmp/DeepSeek-R1-DRAFT-Qwen2.5-0.5B       --dataset-name sharegpt         --dataset-path /hy-tmp/sharegpt.json   --profile --speculative-len 1 --num-prompts 300 --request-rate 10 1>> a124new.log 2>> a124new_error.log 
# python run_benchmark_tests.py --strategy ilp --sub-strategy  nospec --model /hy-tmp/ --draft-model /hy-tmp/DeepSeek-R1-DRAFT-Qwen2.5-0.5B       --dataset-name sharegpt         --dataset-path /hy-tmp/sharegpt.json   --profile --speculative-len 2 --num-prompts 300 --request-rate 10 1>> a124new.log 2>> a124new_error.log 
# python run_benchmark_tests.py --strategy ilp --sub-strategy  nospec --model /hy-tmp/ --draft-model /hy-tmp/DeepSeek-R1-DRAFT-Qwen2.5-0.5B       --dataset-name sharegpt         --dataset-path /hy-tmp/sharegpt.json   --profile --speculative-len 3 --num-prompts 300 --request-rate 10 1>> a124new.log 2>> a124new_error.log 
# python run_benchmark_tests.py --strategy ilp --sub-strategy  nospec --model /hy-tmp/ --draft-model /hy-tmp/DeepSeek-R1-DRAFT-Qwen2.5-0.5B       --dataset-name sharegpt         --dataset-path /hy-tmp/sharegpt.json   --profile --speculative-len 4 --num-prompts 300 --request-rate 10 1>> a124new.log 2>> a124new_error.log 


# python run_benchmark_tests.py --strategy ilp --sub-strategy daspec --model /data/model/deepseek-aiDeepSeek-R1-Distill-Qwen-7B         --dataset-name sharegpt         --dataset-path /data/sharegpt.json   --num-prompts 100 --request-rate 10 1>> a122new.log 2>> a122new_error.log 
#python run_benchmark_tests.py --strategy ilp --sub-strategy nospec --model /data/model/deepseek-aiDeepSeek-R1-Distill-Qwen-7B         --dataset-name sharegpt         --dataset-path /data/sharegpt.json   --num-prompts 100 --request-rate 10 1>> a122new.log 2>> a122new_error.log 
# python run_benchmark_tests.py --strategy ilp --sub-strategy daspec --model /data/model/deepseek-aiDeepSeek-R1-Distill-Qwen-7B         --dataset-name sharegpt         --dataset-path /data/sharegpt.json   --num-prompts 100 --request-rate 5 1>> a122new.log 2>> a122new_error.log 
# python run_benchmark_tests.py --strategy ilp --sub-strategy nospec --model /data/model/deepseek-aiDeepSeek-R1-Distill-Qwen-7B         --dataset-name sharegpt         --dataset-path /data/sharegpt.json   --num-prompts 100 --request-rate 5 1>> a122new.log 2>> a122new_error.log
# python run_benchmark_tests.py --strategy ilp --sub-strategy daspec --model /data/model/deepseek-aiDeepSeek-R1-Distill-Qwen-7B         --dataset-name sharegpt         --dataset-path /data/sharegpt.json   --num-prompts 100 --request-rate 10 1>> a122new.log 2>> a122new_error.log 
# python run_benchmark_tests.py --strategy ilp --sub-strategy nospec --model /data/model/deepseek-aiDeepSeek-R1-Distill-Qwen-7B         --dataset-name sharegpt         --dataset-path /data/sharegpt.json   --num-prompts 100 --request-rate 10 1>> a122new.log 2>> a122new_error.log